name: Sync to otherr repo

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to destination repo
        env:
          DESTPAT: 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
          DESTREPO: ShopCheapUg-com/ShopCheapMobile
          DESTBRANCH: staging
        run: |
          set -euo pipefail
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          echo "Destination repo (owner/name): ${DESTREPO}"
          echo "PAT:${DESTPAT} "
          echo "Destination branch: ${DESTBRANCH}"
          echo "Destination URL (no token): https://github.com/${DESTREPO}.git"

          git remote add dest "https://x-access-token:${DESTPAT}@github.com/${DESTREPO}.git"
          git push --force dest HEAD:${DESTBRANCH}
